config/routes.rb
Rails.application.routes.draw do
  root 'performances#index'
  resources :performances
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/performance.rb
class Performance < ApplicationRecord
  attribute :show_dates, DateRangeType.new
  validates :title, presence: true
  validate :not_empty_dates
  validate :end_after_start, :if => Proc.new { |obj| obj.dates_present? }
  validate :not_overlap

  scope :overlaps, ->(start_date, end_date) do
    where "(((show_dates).start_date <= ?) and ((show_dates).end_date >= ?))", end_date, start_date
  end

  def dates_present?
    show_dates.start_date && show_dates.end_date
  end

  def overlaps
    Performance.overlaps show_dates.start_date, show_dates.end_date
  end

  private

  def not_empty_dates
    unless dates_present?
      errors.add(:show_dates, "Dates can't be blank")
    end
  end

  def end_after_start
    if show_dates.start_date > show_dates.end_date
      errors.add(:show_dates, "End date can't be before start date")
    end
  end

  def not_overlap
    if overlaps.exists?
      errors.add(:show_dates, "Range can't overlap with an existing one")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def index
    @performances = Performance.all
  end

  def new
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(performance_params)
    if @performance.save
      redirect_to performances_path, notice: "Performance created!"
    else
      render :new
    end
  end

  def destroy
    Performance.find(params[:id]).destroy
    redirect_to performances_url
  end

  private

  def performance_params
    params.require(:performance).permit(:title, show_dates: [:start_date, :end_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theatre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/performances/index.html.erb
<div>
  <%= link_to 'New', new_performance_path%>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td><%=performance.title%></td>
        <td><%=performance.show_dates%></td>
        <td><%=link_to "delete", performance, method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/performances/new.html.erb
<% if @performance.errors.full_messages.any? %>
  <% @performance.errors.full_messages.each do |error_message| %>
    <%= error_message %> <br />
  <% end %>
<% end %>

<%= form_for @performance do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <%= f.fields :show_dates, model: f.object.show_dates do |sd_field| %>
    <%= sd_field.label :start_date %>
    <%= sd_field.date_field :start_date, required: true %>
    <%= sd_field.label :end_date %>
    <%= sd_field.date_field :end_date, required: true %>
  <% end %>

  <%= f.submit 'Create'%>
<% end %>